# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ee613_team.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ee613_team.proto',
  package='ee613_team',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x65\x65\x36\x31\x33_team.proto\x12\nee613_team\"g\n\tFood_Info\x12\x0f\n\x07menu_id\x18\x01 \x01(\x05\x12\x11\n\tmenu_name\x18\x02 \x01(\t\x12\x12\n\nmenu_price\x18\x03 \x01(\x05\x12\x10\n\x08menu_num\x18\x04 \x01(\x05\x12\x10\n\x08menu_img\x18\x05 \x01(\x0c\"N\n\rLogin_Respond\x12\x15\n\rlogin_success\x18\x01 \x01(\x08\x12&\n\x07\x66\x64_info\x18\x02 \x03(\x0b\x32\x15.ee613_team.Food_Info\"(\n\x0eSignin_Respond\x12\x16\n\x0esignin_success\x18\x01 \x01(\x08\"(\n\tUser_Info\x12\x0c\n\x04u_id\x18\x01 \x01(\t\x12\r\n\x05u_pwd\x18\x02 \x01(\t\",\n\x07Orders_\x12\x0f\n\x07menu_id\x18\x01 \x01(\x05\x12\x10\n\x08menu_num\x18\x02 \x01(\x05\"j\n\nFood_Order\x12$\n\x07orders_\x18\x01 \x03(\x0b\x32\x13.ee613_team.Orders_\x12\x12\n\ntotal_cost\x18\x02 \x01(\x05\x12\"\n\x03uif\x18\x03 \x01(\x0b\x32\x15.ee613_team.User_Info\"9\n\rOrder_Respond\x12\x0e\n\x06istrue\x18\x01 \x01(\x08\x12\x18\n\x10remaining_points\x18\x02 \x01(\x05\",\n\x10Remaining_Points\x12\x18\n\x10remaining_points\x18\x01 \x01(\x05\"Q\n\x10Recharge_Request\x12\"\n\x03uif\x18\x01 \x01(\x0b\x32\x15.ee613_team.User_Info\x12\x19\n\x11recharging_points\x18\x02 \x01(\x05\x32\xe4\x02\n\x0c\x45\x45\x36\x31\x33_Team_P\x12<\n\x06Login_\x12\x15.ee613_team.User_Info\x1a\x19.ee613_team.Login_Respond\"\x00\x12=\n\x06Signin\x12\x15.ee613_team.User_Info\x1a\x1a.ee613_team.Signin_Respond\"\x00\x12\x41\n\nOrder_Food\x12\x16.ee613_team.Food_Order\x1a\x19.ee613_team.Order_Respond\"\x00\x12\x44\n\x0bPoint_Check\x12\x15.ee613_team.User_Info\x1a\x1c.ee613_team.Remaining_Points\"\x00\x12N\n\x0ePoint_Recharge\x12\x1c.ee613_team.Recharge_Request\x1a\x1c.ee613_team.Remaining_Points\"\x00\x62\x06proto3'
)




_FOOD_INFO = _descriptor.Descriptor(
  name='Food_Info',
  full_name='ee613_team.Food_Info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='menu_id', full_name='ee613_team.Food_Info.menu_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='menu_name', full_name='ee613_team.Food_Info.menu_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='menu_price', full_name='ee613_team.Food_Info.menu_price', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='menu_num', full_name='ee613_team.Food_Info.menu_num', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='menu_img', full_name='ee613_team.Food_Info.menu_img', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=135,
)


_LOGIN_RESPOND = _descriptor.Descriptor(
  name='Login_Respond',
  full_name='ee613_team.Login_Respond',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='login_success', full_name='ee613_team.Login_Respond.login_success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fd_info', full_name='ee613_team.Login_Respond.fd_info', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=215,
)


_SIGNIN_RESPOND = _descriptor.Descriptor(
  name='Signin_Respond',
  full_name='ee613_team.Signin_Respond',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='signin_success', full_name='ee613_team.Signin_Respond.signin_success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=257,
)


_USER_INFO = _descriptor.Descriptor(
  name='User_Info',
  full_name='ee613_team.User_Info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='u_id', full_name='ee613_team.User_Info.u_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='u_pwd', full_name='ee613_team.User_Info.u_pwd', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=299,
)


_ORDERS_ = _descriptor.Descriptor(
  name='Orders_',
  full_name='ee613_team.Orders_',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='menu_id', full_name='ee613_team.Orders_.menu_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='menu_num', full_name='ee613_team.Orders_.menu_num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=345,
)


_FOOD_ORDER = _descriptor.Descriptor(
  name='Food_Order',
  full_name='ee613_team.Food_Order',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='orders_', full_name='ee613_team.Food_Order.orders_', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_cost', full_name='ee613_team.Food_Order.total_cost', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uif', full_name='ee613_team.Food_Order.uif', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=453,
)


_ORDER_RESPOND = _descriptor.Descriptor(
  name='Order_Respond',
  full_name='ee613_team.Order_Respond',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='istrue', full_name='ee613_team.Order_Respond.istrue', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='remaining_points', full_name='ee613_team.Order_Respond.remaining_points', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=455,
  serialized_end=512,
)


_REMAINING_POINTS = _descriptor.Descriptor(
  name='Remaining_Points',
  full_name='ee613_team.Remaining_Points',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='remaining_points', full_name='ee613_team.Remaining_Points.remaining_points', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=514,
  serialized_end=558,
)


_RECHARGE_REQUEST = _descriptor.Descriptor(
  name='Recharge_Request',
  full_name='ee613_team.Recharge_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uif', full_name='ee613_team.Recharge_Request.uif', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recharging_points', full_name='ee613_team.Recharge_Request.recharging_points', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=560,
  serialized_end=641,
)

_LOGIN_RESPOND.fields_by_name['fd_info'].message_type = _FOOD_INFO
_FOOD_ORDER.fields_by_name['orders_'].message_type = _ORDERS_
_FOOD_ORDER.fields_by_name['uif'].message_type = _USER_INFO
_RECHARGE_REQUEST.fields_by_name['uif'].message_type = _USER_INFO
DESCRIPTOR.message_types_by_name['Food_Info'] = _FOOD_INFO
DESCRIPTOR.message_types_by_name['Login_Respond'] = _LOGIN_RESPOND
DESCRIPTOR.message_types_by_name['Signin_Respond'] = _SIGNIN_RESPOND
DESCRIPTOR.message_types_by_name['User_Info'] = _USER_INFO
DESCRIPTOR.message_types_by_name['Orders_'] = _ORDERS_
DESCRIPTOR.message_types_by_name['Food_Order'] = _FOOD_ORDER
DESCRIPTOR.message_types_by_name['Order_Respond'] = _ORDER_RESPOND
DESCRIPTOR.message_types_by_name['Remaining_Points'] = _REMAINING_POINTS
DESCRIPTOR.message_types_by_name['Recharge_Request'] = _RECHARGE_REQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Food_Info = _reflection.GeneratedProtocolMessageType('Food_Info', (_message.Message,), {
  'DESCRIPTOR' : _FOOD_INFO,
  '__module__' : 'ee613_team_pb2'
  # @@protoc_insertion_point(class_scope:ee613_team.Food_Info)
  })
_sym_db.RegisterMessage(Food_Info)

Login_Respond = _reflection.GeneratedProtocolMessageType('Login_Respond', (_message.Message,), {
  'DESCRIPTOR' : _LOGIN_RESPOND,
  '__module__' : 'ee613_team_pb2'
  # @@protoc_insertion_point(class_scope:ee613_team.Login_Respond)
  })
_sym_db.RegisterMessage(Login_Respond)

Signin_Respond = _reflection.GeneratedProtocolMessageType('Signin_Respond', (_message.Message,), {
  'DESCRIPTOR' : _SIGNIN_RESPOND,
  '__module__' : 'ee613_team_pb2'
  # @@protoc_insertion_point(class_scope:ee613_team.Signin_Respond)
  })
_sym_db.RegisterMessage(Signin_Respond)

User_Info = _reflection.GeneratedProtocolMessageType('User_Info', (_message.Message,), {
  'DESCRIPTOR' : _USER_INFO,
  '__module__' : 'ee613_team_pb2'
  # @@protoc_insertion_point(class_scope:ee613_team.User_Info)
  })
_sym_db.RegisterMessage(User_Info)

Orders_ = _reflection.GeneratedProtocolMessageType('Orders_', (_message.Message,), {
  'DESCRIPTOR' : _ORDERS_,
  '__module__' : 'ee613_team_pb2'
  # @@protoc_insertion_point(class_scope:ee613_team.Orders_)
  })
_sym_db.RegisterMessage(Orders_)

Food_Order = _reflection.GeneratedProtocolMessageType('Food_Order', (_message.Message,), {
  'DESCRIPTOR' : _FOOD_ORDER,
  '__module__' : 'ee613_team_pb2'
  # @@protoc_insertion_point(class_scope:ee613_team.Food_Order)
  })
_sym_db.RegisterMessage(Food_Order)

Order_Respond = _reflection.GeneratedProtocolMessageType('Order_Respond', (_message.Message,), {
  'DESCRIPTOR' : _ORDER_RESPOND,
  '__module__' : 'ee613_team_pb2'
  # @@protoc_insertion_point(class_scope:ee613_team.Order_Respond)
  })
_sym_db.RegisterMessage(Order_Respond)

Remaining_Points = _reflection.GeneratedProtocolMessageType('Remaining_Points', (_message.Message,), {
  'DESCRIPTOR' : _REMAINING_POINTS,
  '__module__' : 'ee613_team_pb2'
  # @@protoc_insertion_point(class_scope:ee613_team.Remaining_Points)
  })
_sym_db.RegisterMessage(Remaining_Points)

Recharge_Request = _reflection.GeneratedProtocolMessageType('Recharge_Request', (_message.Message,), {
  'DESCRIPTOR' : _RECHARGE_REQUEST,
  '__module__' : 'ee613_team_pb2'
  # @@protoc_insertion_point(class_scope:ee613_team.Recharge_Request)
  })
_sym_db.RegisterMessage(Recharge_Request)



_EE613_TEAM_P = _descriptor.ServiceDescriptor(
  name='EE613_Team_P',
  full_name='ee613_team.EE613_Team_P',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=644,
  serialized_end=1000,
  methods=[
  _descriptor.MethodDescriptor(
    name='Login_',
    full_name='ee613_team.EE613_Team_P.Login_',
    index=0,
    containing_service=None,
    input_type=_USER_INFO,
    output_type=_LOGIN_RESPOND,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Signin',
    full_name='ee613_team.EE613_Team_P.Signin',
    index=1,
    containing_service=None,
    input_type=_USER_INFO,
    output_type=_SIGNIN_RESPOND,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Order_Food',
    full_name='ee613_team.EE613_Team_P.Order_Food',
    index=2,
    containing_service=None,
    input_type=_FOOD_ORDER,
    output_type=_ORDER_RESPOND,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Point_Check',
    full_name='ee613_team.EE613_Team_P.Point_Check',
    index=3,
    containing_service=None,
    input_type=_USER_INFO,
    output_type=_REMAINING_POINTS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Point_Recharge',
    full_name='ee613_team.EE613_Team_P.Point_Recharge',
    index=4,
    containing_service=None,
    input_type=_RECHARGE_REQUEST,
    output_type=_REMAINING_POINTS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EE613_TEAM_P)

DESCRIPTOR.services_by_name['EE613_Team_P'] = _EE613_TEAM_P

# @@protoc_insertion_point(module_scope)
