# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import ee613_team_pb2 as ee613__team__pb2


class EE613_Team_PStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login_ = channel.unary_unary(
                '/ee613_team.EE613_Team_P/Login_',
                request_serializer=ee613__team__pb2.User_Info.SerializeToString,
                response_deserializer=ee613__team__pb2.Login_Respond.FromString,
                )
        self.Signin = channel.unary_unary(
                '/ee613_team.EE613_Team_P/Signin',
                request_serializer=ee613__team__pb2.User_Info.SerializeToString,
                response_deserializer=ee613__team__pb2.Signin_Respond.FromString,
                )
        self.Order_Food = channel.unary_unary(
                '/ee613_team.EE613_Team_P/Order_Food',
                request_serializer=ee613__team__pb2.Food_Order.SerializeToString,
                response_deserializer=ee613__team__pb2.Order_Respond.FromString,
                )
        self.Point_Check = channel.unary_unary(
                '/ee613_team.EE613_Team_P/Point_Check',
                request_serializer=ee613__team__pb2.User_Info.SerializeToString,
                response_deserializer=ee613__team__pb2.Remaining_Points.FromString,
                )
        self.Point_Recharge = channel.unary_unary(
                '/ee613_team.EE613_Team_P/Point_Recharge',
                request_serializer=ee613__team__pb2.Recharge_Request.SerializeToString,
                response_deserializer=ee613__team__pb2.Remaining_Points.FromString,
                )


class EE613_Team_PServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login_(self, request, context):
        """Login and then Food_Info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Signin(self, request, context):
        """Signin
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Order_Food(self, request, context):
        """For food order, we need information of user, menus and qunatity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Point_Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Point_Recharge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EE613_Team_PServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login_': grpc.unary_unary_rpc_method_handler(
                    servicer.Login_,
                    request_deserializer=ee613__team__pb2.User_Info.FromString,
                    response_serializer=ee613__team__pb2.Login_Respond.SerializeToString,
            ),
            'Signin': grpc.unary_unary_rpc_method_handler(
                    servicer.Signin,
                    request_deserializer=ee613__team__pb2.User_Info.FromString,
                    response_serializer=ee613__team__pb2.Signin_Respond.SerializeToString,
            ),
            'Order_Food': grpc.unary_unary_rpc_method_handler(
                    servicer.Order_Food,
                    request_deserializer=ee613__team__pb2.Food_Order.FromString,
                    response_serializer=ee613__team__pb2.Order_Respond.SerializeToString,
            ),
            'Point_Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Point_Check,
                    request_deserializer=ee613__team__pb2.User_Info.FromString,
                    response_serializer=ee613__team__pb2.Remaining_Points.SerializeToString,
            ),
            'Point_Recharge': grpc.unary_unary_rpc_method_handler(
                    servicer.Point_Recharge,
                    request_deserializer=ee613__team__pb2.Recharge_Request.FromString,
                    response_serializer=ee613__team__pb2.Remaining_Points.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ee613_team.EE613_Team_P', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EE613_Team_P(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login_(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ee613_team.EE613_Team_P/Login_',
            ee613__team__pb2.User_Info.SerializeToString,
            ee613__team__pb2.Login_Respond.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Signin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ee613_team.EE613_Team_P/Signin',
            ee613__team__pb2.User_Info.SerializeToString,
            ee613__team__pb2.Signin_Respond.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Order_Food(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ee613_team.EE613_Team_P/Order_Food',
            ee613__team__pb2.Food_Order.SerializeToString,
            ee613__team__pb2.Order_Respond.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Point_Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ee613_team.EE613_Team_P/Point_Check',
            ee613__team__pb2.User_Info.SerializeToString,
            ee613__team__pb2.Remaining_Points.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Point_Recharge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ee613_team.EE613_Team_P/Point_Recharge',
            ee613__team__pb2.Recharge_Request.SerializeToString,
            ee613__team__pb2.Remaining_Points.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
